require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.color"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comments"
require "user.gitsigns"
--require "user.nvimTree" -- never turn this thing
require "user.lualine"
require "user.toggleterm"
require "user.indentline"
--require "user.whichkey"
require "user.autocommands"
require "user.harpoon"
require "user.format"
require "user.undoTree"
--[[ require "user.fzf" ]]
require "user.background"
