vim.api.nvim_set_keymap('n','<F12>',':lua require("harpoon.mark").add_file()<CR>',{noremap=true})
vim.api.nvim_set_keymap('n','<C-e>',':lua require("harpoon.ui").toggle_quick_menu()<CR>',{noremap=true})
vim.api.nvim_set_keymap('n','<F2>',':lua require("harpoon.ui").nav_file(1)<CR>',{noremap=true})
vim.api.nvim_set_keymap('n','<F3>',':lua require("harpoon.ui").nav_file(2)<CR>',{noremap=true})
vim.api.nvim_set_keymap('n','<F4>',':lua require("harpoon.ui").nav_file(3)<CR>',{noremap=true})
vim.api.nvim_set_keymap('n','<F5>',':lua require("harpoon.ui").nav_file(4)<CR>',{noremap=true})
